name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - run: npm test
      # - name: npm run semantic-release
      #   if: github.ref == 'refs/heads/main'
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: npm run semantic-release
